eureka:
  client:
    serviceUrl:
      defaultZone: http://lihy:520@localhost:8088/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html

#测试自动刷新的配置属性
profile: lihy

spring:
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  #zipkin服务地址及采样比例
  zipkin:
    base-url: http://localhost:8000
  sleuth:
    sampler:
      percentage: 1.0

#feign远程调用配置开启熔断
feign:
  hystrix:
    enabled: true
#hystrix熔断机制
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

#zuul的路由配置
zuul:
  routes:
    view-user-service: /user-service/**