eureka:
  client:
    serviceUrl:
      defaultZone: http://lihy:520@localhost:8088/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html

#测试自动刷新的配置属性
profile: lihy
#rabbitmq配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#feign远程调用配置开启熔断
feign:
  hystrix:
    enabled: true